name: Attach Lunar agent
description: Attaches the Lunar agent to the current CI job
branding:
  icon: "sunrise"
  color: "green"
author: Earthly technologies
inputs:
  github-token:
    description: >
      The GitHub token used to make authenticated API requests. Requires permissions to:
      1) Clone manifest repo
      2) ...
    default: ${{ github.token }}
    required: true
  manifest-url:
    description: >
      Lunar manifest repo URL, in the form of: github://<org>/<repo>@<branch>
    required: true
  hub-token:
    required: true
  hub-host:
    required: true
  hub-grpc-port:
    default: 443
    required: false
  hub-http-port:
    default: 443
    required: false
  log-level:
    description: >
      Lunar log level.
    default: debug
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure git credentials
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        GITHUB_USERNAME=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/user | jq '.login')

        git config --global credential.helper store
        echo "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com" > ~/.git-credentials
        chmod 600 ~/.git-credentials
      shell: bash

    - name: Download Lunar binary
      env:
        FORCE_COLOR: 1
      run: |
        mkdir -p /tmp/lunar/bin
        curl -L https://github.com/earthly/lunar-dist/releases/download/v1.0.0/lunar-linux-amd64 -o /tmp/lunar/bin/lunar
        chmod +x /tmp/lunar/bin/lunar;
        echo "lunar downloaded to /tmp/lunar/bin/lunar";
      shell: bash

    - name: Fetch manifest
      env:
        FORCE_COLOR: 1
        LUNAR_HUB_TOKEN: ${{ inputs.hub-token }}
        LUNAR_GITHUB_TOKEN: ${{ inputs.github-token }}
        LUNAR_HUB_HOST: ${{ inputs.hub-host }}
        LUNAR_HUB_GRPC_PORT: ${{ inputs.hub-grpc-port }}
        LUNAR_HUB_HTTP_PORT: ${{ inputs.hub-http-port }}
      run: |
          /tmp/lunar/bin/lunar install ${{ inputs.manifest-url }}
      shell: bash

    - name: Attach to job
      env:
        FORCE_COLOR: 1
        LUNAR_HUB_TOKEN: ${{ inputs.hub-token }}
        LUNAR_GITHUB_TOKEN: ${{ inputs.github-token }}
        LUNAR_HUB_HOST: ${{ inputs.hub-host }}
        LUNAR_HUB_GRPC_PORT: ${{ inputs.hub-grpc-port }}
        LUNAR_HUB_HTTP_PORT: ${{ inputs.hub-http-port }}
      run: |
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
        runner_id=$(pid=$$; while [ "$pid" -ne 1 ] && [ -e "/proc/$pid" ]; do ppid=$(awk '/^PPid:/ {print $2}' /proc/$pid/status); [ "$ppid" -eq 1 ] && echo "$pid"; pid=$ppid; done)
        echo "Attaching agent to runner process with pid: $runner_id"
        /tmp/lunar/bin/lunar --pid=$runner_id > /tmp/lunar/logs.txt 2>&1 &
        echo $! > /tmp/lunar/agent.pid
      shell: bash

    - name: Tests
      run: |
        cat /tmp/lunar/agent.pid
        cat /tmp/lunar/logs.txt
        pid=$(cat /tmp/lunar/agent.pid); while [ "$pid" -ne 1 ]; do echo "$(ps -p $pid -o pid=,ppid=,cmd=)"; pid=$(ps -p $pid -o ppid=); done; ps -p 1 -o pid=,ppid=,cmd=
      shell: bash

