name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lunar setup
        uses: ./sync-config
        with:
          manifest-url: "github://pantalasa-cronos/lunar@main"
          hub-token: "${{ secrets.LUNAR_HUB_TOKEN }}"
          hub-host: cronos.demo.earthly.dev
          lunar-version: v1.1.1
